config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products do
    resources :reviews
  end
  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :user
  belongs_to :category
  has_many :reviews

  has_attached_file :product_img, styles: { product_index: "350x350>", product_show: "350x500>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :product_img, content_type: /\Aimage\/.*\z/

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
      if params[:category].blank?
      @products = Product.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @products = Product.where(:category_id => @category_id).order("created_at DESC")
    end
  end

  def show
    if @product.reviews.blank?
      @average_review = 0
    else
      @average_review = @product.reviews.average(:rating).round(2)
    end
  end

  def new
    @product = current_user.products.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def create
    @product = current_user.products.build(product_params)
    @product.category_id = params[:category_id]

    if @product.save
      redirect_to root_path
    end

  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def update
    @product.category_id = params[:category_id]
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to root_path
  end

  private

    def product_params
      params.require(:product).permit(:name, :description, :price_in_cents, :category_id, :product_img)
    end

    def find_product
      @product = Product.find(params[:id])
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_product
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.product_id = @product.id
    @review.user_id = current_user.id

      if @review.save
        redirect_to product_path(@product)
      else
        render 'new'
      end

  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to product_path(@product)
    else
      render 'edit'
    end
  end

  def destroy
      @review.destroy
      redirect_to product_path(@product)
  end

  private

    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def find_product
      @product = Product.find(params[:product_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JapanProduct Review Site</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default banner-img">

      <div class="container">

        <div class="navbar-header">
          <%= link_to 'Japan Product Review', root_path, class: "navbar-brand" %>
        </div>

        <ul class="nav navbar-nav navbar-right">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
            aria-expanded="false">Categories<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% Category.all.each do |category| %>
                <li class="<%= 'active' if params[:category] == category.name %>">
                  <%= link_to category.name, products_path(category: category.name), class: "link" %>
                </li>
              <% end %>
            </ul>
          </li>

          <% if user_signed_in? %>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <li><%= link_to 'Add Product', new_product_path %></li>
          <% else %>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>
          <li><div id="main">
            <span style="cursor:pointer" onclick="openNav()">&#9776; About</span>
          </div></li>

        </ul>

      </div>

    </nav>

    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a href="#">About</a>
    </div>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>

  </body>

  <script>
  function openNav() {
      document.getElementById("mySidenav").style.width = "250px";
      document.body.style.marginLeft = "250px";
      document.html.style.backgroundColor = "rgba(0,0,0,0.4)";
  }

  function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
      document.body.style.marginLeft= "0";
      document.body.style.backgroundColor = "#F2F4F4";
  }
  </script>

<ain></ain></html>

app/views/products/_form.html.erb
<%= simple_form_for @product, :html => { :multipart => true } do |f| %>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
  <%= f.file_field :product_img %>
  <%= f.input :name, label: "Product Name" %>
  <%= f.input :description %>
  <%= f.input :price_in_cents %>
  <%= f.button :submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= simple_form_for @product, :html => { :multipart => true } do |f| %>
  <%= f.select :category_id, @categories %>
  <%= f.file_field :product_img %>
  <%= f.input :name, label: "Product Name" %>
  <%= f.input :description %>
  <%= f.input :price_in_cents %>
  <%= f.button :submit %>
<% end %>

app/views/products/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @products.count == 0 %>
  <h1>There are no products in that category</h1>

  <% else %>

  <div class="row">

      <% @products.each do |product| %>

        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="product-box">
            <a href="/products/<%= product.id %>">
              <%= image_tag product.product_img.url(:product_index), class: "product-img" %>
            </a>
              <div class="product-box-name">
                <%= product.name %>
              </div>
          </div>
        </div>

    <% end %>

  </div>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag @product.product_img.url (:product_show), class: "product-show" %>
  </div>
  <div class="col-md-8">
    <h2><%= @product.name %></h2>
    <h2>Average Rating</h2>
    <div class="average-review-rating" data-score="<%= @average_review %>"></div>
    <span>Based On <%= @product.reviews.count %> reviews</span>
    <h4>Category: <%= @product.category.name %></h4>
    <p><%= @product.description %></p>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <!-- review and ratings will go here -->

  <%= render @product.reviews %>

  <div>
    <%= link_to "Add Review", new_product_review_path(@product)  %>
    <%= link_to 'Back', root_path %>
  </div>

  </div>
</div>


<% if user_signed_in? %>

  <% if @product.user_id == current_user.id %>

  <%= link_to 'Edit', edit_product_path(@product) %>
  <%= link_to 'Delete', product_path(@product), method: :delete, data: { confirm: "Are you sure?"} %>

  <% end %>

<% end %>

<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  })
</script>

app/views/reviews/_form.html.erb
<%= simple_form_for([@product, @product.reviews.build]) do |f| %>
  <div id="rating-form">
    <label>Rating</label>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit %>

<% end %>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<div class="review-rating" data-score="<%= review.rating %>"></div>
<p><%= review.comment %></p>


<% if user_signed_in? %>

  <% if review.user_id == current_user.id %>

<%= link_to 'Edit', edit_product_review_path(review.product, review) %>
<%= link_to 'Delete', product_review_path(review.product, review), method: :delete, data: {confirm: "Are you sure?"} %>

  <% end %>

<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= simple_form_for([@product, @review]) do |f| %>
  <div id="rating-form">
    <label>Rating</label>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>